#!/bin/bash
luarocks install --lua-version 5.4 xml2lua
# if macos
# * brew install openssl@3 (or whatever openssl version)
# * brew reinstall m4
# luarocks install http CRYPTO_DIR=/opt/homebrew/opt/openssl@3 OPENSSL_DIR=/opt/homebrew/opt/openssl@3
luarocks install --lua-version 5.4 http
