#!/bin/bash
luarocks install --local --force xml2lua
# if macos
# * brew install openssl@3 (or whatever openssl version)
# * brew reinstall m4
luarocks install --local http CRYPTO_DIR=$(brew --prefix openssl) OPENSSL_DIR=$(brew --prefix openssl)

# http relies on require('lpeg') but luarocks installed it as lpeg_patters
# at some point. so if running fetch-mvn-sources fails, try the below
# sudo ln -s /opt/local/share/luarocks/share/lua/<lua-version>/lpeg_patterns/ /opt/local/share/luarocks/share/lua/<lua-version>/lpeg/

